// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GOAPIGOGO.Models;

public partial class AdmOperator
{
    public int idAdmOperator { get; set; }

    public string cellphone { get; set; }

    public string email { get; set; }
}