// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace GOAPIGOGO.Models;

public partial class Operator
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int idOperator { get; set; }

    public string cellphone { get; set; }

    public string email { get; set; }

    //public virtual ICollection<SchedulexOperator> SchedulexOperators { get; set; } = new List<SchedulexOperator>();
}