// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace GOAPIGOGO.Models
{
    public partial class ReadUserByIDResult
    {
        public int idUser { get; set; }
        public string email { get; set; }
    }
}
