// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GOAPIGOGO.Models;

public partial class SchedulexFacility
{
    public int idSchedulexFacility { get; set; }

    public DateTime? date { get; set; }

    public TimeSpan? beginningHour { get; set; }

    public TimeSpan? finishingHour { get; set; }

    public int? idFacilities { get; set; }

    public virtual Facility idFacilitiesNavigation { get; set; }
}