// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIWEBGO.Models;

public partial class User
{
    public int idUser { get; set; }

    public string email { get; set; }

    public virtual ICollection<Equipment> Equipment { get; set; } = new List<Equipment>();

    public virtual ICollection<Facility> Facilities { get; set; } = new List<Facility>();
}