// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LayoutTemplateWebApp.Models;

public partial class AdmOperator
{
    public int IdAdmOperator { get; set; }

    public string Cellphone { get; set; }

    public string Email { get; set; }
}