// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LayoutTemplateWebApp.Models;

public partial class Classroom
{
    public string idClassroom { get; set; }

    public string idFacilities { get; set; }

    public virtual Facility idFacilitiesNavigation { get; set; }
}