// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LayoutTemplateWebApp.Models;

public partial class Equipment
{
    public int IdEquipment { get; set; }

    public bool? Availability { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int? IdUser { get; set; }

    public string Condition { get; set; }

    public virtual User IdUserNavigation { get; set; }

    public virtual ICollection<SchedulexEquipment> SchedulexEquipment { get; set; } = new List<SchedulexEquipment>();
}