// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace LayoutTemplateWebApp.Models;

public partial class GestionOperatorsContext : DbContext
{
    public GestionOperatorsContext(DbContextOptions<GestionOperatorsContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AdmOperator> AdmOperator { get; set; }

    public virtual DbSet<Classroom> Classroom { get; set; }

    public virtual DbSet<Equipment> Equipment { get; set; }

    public virtual DbSet<Facility> Facility { get; set; }

    public virtual DbSet<Laboratory> Laboratory { get; set; }

    public virtual DbSet<Operator> Operator { get; set; }

    public virtual DbSet<SchedulexEquipment> SchedulexEquipment { get; set; }

    public virtual DbSet<SchedulexFacility> SchedulexFacility { get; set; }

    public virtual DbSet<SchedulexOperator> SchedulexOperator { get; set; }

    public virtual DbSet<User> User { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AdmOperator>(entity =>
        {
            entity.HasKey(e => e.IdAdmOperator).HasName("PK__AdmOpera__DF5A81DC05D49093");

            entity.Property(e => e.IdAdmOperator).HasColumnName("idAdmOperator");
            entity.Property(e => e.Cellphone)
                .HasMaxLength(20)
                .HasColumnName("cellphone");
            entity.Property(e => e.Email)
                .HasMaxLength(255)
                .HasColumnName("email");
        });

        modelBuilder.Entity<Classroom>(entity =>
        {
            entity.HasKey(e => e.IdClassroom).HasName("PK__Classroo__DF3B575D5314FD60");

            entity.Property(e => e.IdClassroom)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("idClassroom");
            entity.Property(e => e.IdFacilities).HasColumnName("idFacilities");

            entity.HasOne(d => d.IdFacilitiesNavigation).WithMany(p => p.Classroom)
                .HasForeignKey(d => d.IdFacilities)
                .HasConstraintName("FK__Classroom__idFac__38996AB5");
        });

        modelBuilder.Entity<Equipment>(entity =>
        {
            entity.HasKey(e => e.IdEquipment).HasName("PK__Equipmen__F5087F02A448AE87");

            entity.Property(e => e.IdEquipment).HasColumnName("idEquipment");
            entity.Property(e => e.Availability).HasColumnName("availability");
            entity.Property(e => e.Condition)
                .HasMaxLength(255)
                .HasColumnName("condition");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.IdUser).HasColumnName("idUser");
            entity.Property(e => e.Name)
                .HasMaxLength(255)
                .HasColumnName("name");

            entity.HasOne(d => d.IdUserNavigation).WithMany(p => p.Equipment)
                .HasForeignKey(d => d.IdUser)
                .HasConstraintName("FK__Equipment__idUse__2D27B809");
        });

        modelBuilder.Entity<Facility>(entity =>
        {
            entity.HasKey(e => e.IdFacilities).HasName("PK__Facility__32C12FE6874C4BA1");

            entity.Property(e => e.IdFacilities).HasColumnName("idFacilities");
            entity.Property(e => e.Capacity).HasColumnName("capacity");
            entity.Property(e => e.IdUser).HasColumnName("idUser");

            entity.HasOne(d => d.IdUserNavigation).WithMany(p => p.Facility)
                .HasForeignKey(d => d.IdUser)
                .HasConstraintName("FK__Facility__idUser__32E0915F");
        });

        modelBuilder.Entity<Laboratory>(entity =>
        {
            entity.HasKey(e => e.IdLaboratory).HasName("PK__Laborato__CF6A6A1CAEB86929");

            entity.Property(e => e.IdLaboratory)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("idLaboratory");
            entity.Property(e => e.IdFacilities).HasColumnName("idFacilities");

            entity.HasOne(d => d.IdFacilitiesNavigation).WithMany(p => p.Laboratory)
                .HasForeignKey(d => d.IdFacilities)
                .HasConstraintName("FK__Laborator__idFac__3B75D760");
        });

        modelBuilder.Entity<Operator>(entity =>
        {
            entity.HasKey(e => e.IdOperator).HasName("PK__Operator__DDFD0965DE6C7C29");

            entity.Property(e => e.IdOperator).HasColumnName("idOperator");
            entity.Property(e => e.Cellphone)
                .HasMaxLength(20)
                .HasColumnName("cellphone");
            entity.Property(e => e.Email)
                .HasMaxLength(255)
                .HasColumnName("email");
        });

        modelBuilder.Entity<SchedulexEquipment>(entity =>
        {
            entity.HasKey(e => e.IdSchedulexEquipment).HasName("PK__Schedule__C83BB4F0A55C63A9");

            entity.Property(e => e.IdSchedulexEquipment).HasColumnName("idSchedulexEquipment");
            entity.Property(e => e.BeginningHour)
                .HasPrecision(0)
                .HasColumnName("beginningHour");
            entity.Property(e => e.FinalDate)
                .HasColumnType("date")
                .HasColumnName("finalDate");
            entity.Property(e => e.FinishingHour)
                .HasPrecision(0)
                .HasColumnName("finishingHour");
            entity.Property(e => e.IdEquipment).HasColumnName("idEquipment");
            entity.Property(e => e.InitialDate)
                .HasColumnType("date")
                .HasColumnName("initialDate");

            entity.HasOne(d => d.IdEquipmentNavigation).WithMany(p => p.SchedulexEquipment)
                .HasForeignKey(d => d.IdEquipment)
                .HasConstraintName("FK__Schedulex__idEqu__300424B4");
        });

        modelBuilder.Entity<SchedulexFacility>(entity =>
        {
            entity.HasKey(e => e.IdSchedulexFacility).HasName("PK__Schedule__5181FCD570239712");

            entity.Property(e => e.IdSchedulexFacility).HasColumnName("idSchedulexFacility");
            entity.Property(e => e.BeginningHour)
                .HasPrecision(0)
                .HasColumnName("beginningHour");
            entity.Property(e => e.Date)
                .HasColumnType("date")
                .HasColumnName("date");
            entity.Property(e => e.FinishingHour)
                .HasPrecision(0)
                .HasColumnName("finishingHour");
            entity.Property(e => e.IdFacilities).HasColumnName("idFacilities");

            entity.HasOne(d => d.IdFacilitiesNavigation).WithMany(p => p.SchedulexFacility)
                .HasForeignKey(d => d.IdFacilities)
                .HasConstraintName("FK__Schedulex__idFac__35BCFE0A");
        });

        modelBuilder.Entity<SchedulexOperator>(entity =>
        {
            entity.HasKey(e => e.IdSchedulexOperator).HasName("PK__Schedule__21A3C9903E3E6F74");

            entity.Property(e => e.IdSchedulexOperator).HasColumnName("idSchedulexOperator");
            entity.Property(e => e.BeginningHour)
                .HasPrecision(0)
                .HasColumnName("beginningHour");
            entity.Property(e => e.Day)
                .HasColumnType("date")
                .HasColumnName("day");
            entity.Property(e => e.FinishingHour)
                .HasPrecision(0)
                .HasColumnName("finishingHour");
            entity.Property(e => e.IdOperator).HasColumnName("idOperator");

            entity.HasOne(d => d.IdOperatorNavigation).WithMany(p => p.SchedulexOperator)
                .HasForeignKey(d => d.IdOperator)
                .HasConstraintName("FK__Schedulex__idOpe__2A4B4B5E");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.IdUser).HasName("PK__User__3717C982A6068EA7");

            entity.Property(e => e.IdUser).HasColumnName("idUser");
            entity.Property(e => e.Email)
                .HasMaxLength(255)
                .HasColumnName("email");
        });

        OnModelCreatingGeneratedProcedures(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}