// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace LayoutTemplateWebApp.Models
{
    public partial class GetAvailableEquipmentResult
    {
        public int idEquipment { get; set; }
        public bool? availability { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int? idUser { get; set; }
        public string condition { get; set; }
    }
}
