// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LayoutTemplateWebApp.Models;

public partial class Operator
{
    public int IdOperator { get; set; }

    public string Cellphone { get; set; }

    public string Email { get; set; }

    public virtual ICollection<SchedulexOperator> SchedulexOperator { get; set; } = new List<SchedulexOperator>();
}