// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LayoutTemplateWebApp.Models;

public partial class Operator
{
    public int idOperator { get; set; }

    public string cellphone { get; set; }

    public string email { get; set; }

    public virtual ICollection<SchedulexOperator> SchedulexOperators { get; set; } = new List<SchedulexOperator>();
}