// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace LayoutTemplateWebApp.Models
{
    public partial class ReadAllAdmOperatorsResult
    {
        public int idAdmOperator { get; set; }
        public string cellphone { get; set; }
        public string email { get; set; }
    }
}
