// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace LayoutTemplateWebApp.Models
{
    public partial class ReadAllLaboratoriesResult
    {
        public string idLaboratory { get; set; }
        public string idFacilities { get; set; }
    }
}
