// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace LayoutTemplateWebApp.Models
{
    public partial class ReadAllFacilitiesResult
    {
        public int idFacilities { get; set; }
        public int? capacity { get; set; }
        public int? idUser { get; set; }
    }
}
