// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LayoutTemplateWebApp.Models;

public partial class SchedulexOperator
{
    public int IdSchedulexOperator { get; set; }

    public DateTime? Day { get; set; }

    public TimeSpan? BeginningHour { get; set; }

    public TimeSpan? FinishingHour { get; set; }

    public int? IdOperator { get; set; }

    public virtual Operator IdOperatorNavigation { get; set; }
}