// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace LayoutTemplateWebApp.Models
{
    public partial class SelectAllFromSchedulexFacilityResult
    {
        public int idSchedulexFacility { get; set; }
        public DateTime? date { get; set; }
        public TimeSpan? beginningHour { get; set; }
        public TimeSpan? finishingHour { get; set; }
        public string idFacilities { get; set; }
        public string activityDescription { get; set; }
    }
}
